import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {join,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {preserveDevIziSnapshots} from '../preserve-dev-izi-snapshots.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
async function fixture(){const temp=await mkdtemp(join(tmpdir(),'jumper-dev-build-')),root=join(temp,'assets'),snapshots=join(temp,'snapshots'),manifest={replacements:[],remove:[]};
 for(const slug of ['izigym-lp','izigym-lp-vilaromana']){const path=slug+'/simple/index.html',snapshot=path,generated='new official checkout '+slug,old='existing dev form '+slug;for(const[base,content]of [[root,generated],[snapshots,old]]){await mkdir(dirname(join(base,path)),{recursive:true});await writeFile(join(base,path),content);}const asset=slug+'/_astro/new.js';await mkdir(dirname(join(root,asset)),{recursive:true});await writeFile(join(root,asset),'official only');manifest.replacements.push({slug,path,snapshot,generatedSha256:hash(generated),snapshotSha256:hash(old)});manifest.remove.push({slug,path:asset,generatedSha256:hash('official only')});}
 await mkdir(join(root,'rodeio'));await writeFile(join(root,'rodeio/index.html'),'authorized Rodeio');return{temp,root,snapshots,manifest};}
async function run(t,fn){const f=await fixture();t.after(()=>rm(f.temp,{recursive:true,force:true}));await fn(f);}
test('untouched dev previews retain their bytes and Rodeio remains untouched',t=>run(t,async f=>{await preserveDevIziSnapshots({...f,allowedSlug:'rodeio'});for(const r of f.manifest.replacements)assert.equal(hash(await readFile(join(f.root,r.path))),r.snapshotSha256);for(const r of f.manifest.remove)await assert.rejects(readFile(join(f.root,r.path)),{code:'ENOENT'});assert.equal(await readFile(join(f.root,'rodeio/index.html'),'utf8'),'authorized Rodeio');}));
test('an explicitly allowed IZI preview uses the new source while the sibling stays preserved',t=>run(t,async f=>{await preserveDevIziSnapshots({...f,allowedSlug:'izigym-lp'});for(const r of f.manifest.replacements)assert.equal(hash(await readFile(join(f.root,r.path))),r.slug==='izigym-lp'?r.generatedSha256:r.snapshotSha256);assert.equal(await readFile(join(f.root,'izigym-lp/_astro/new.js'),'utf8'),'official only');await assert.rejects(readFile(join(f.root,'izigym-lp-vilaromana/_astro/new.js')),{code:'ENOENT'});}));
test('tampered snapshot blocks before any candidate is overwritten',t=>run(t,async f=>{await writeFile(join(f.snapshots,f.manifest.replacements[1].snapshot),'tampered');await assert.rejects(preserveDevIziSnapshots({...f,allowedSlug:'rodeio'}),/Snapshot dev alterado/);for(const r of f.manifest.replacements)assert.equal(hash(await readFile(join(f.root,r.path))),r.generatedSha256);}));
test('unrecognized generated page fails closed',t=>run(t,async f=>{await writeFile(join(f.root,f.manifest.replacements[1].path),'future edit');await assert.rejects(preserveDevIziSnapshots({...f,allowedSlug:'rodeio'}),/Build não reconhecido/);const first=f.manifest.replacements[0];assert.equal(hash(await readFile(join(f.root,first.path))),first.generatedSha256);}));
test('unknown generated asset cannot be removed',t=>run(t,async f=>{await writeFile(join(f.root,f.manifest.remove[0].path),'future asset');await assert.rejects(preserveDevIziSnapshots({...f,allowedSlug:'rodeio'}),/Asset não reconhecido/);const first=f.manifest.replacements[0];assert.equal(hash(await readFile(join(f.root,first.path))),first.generatedSha256);}));
test('paths escaping the recorded preview are rejected',t=>run(t,async f=>{f.manifest.replacements[0].path='izigym-lp/../rodeio/index.html';await assert.rejects(preserveDevIziSnapshots({...f,allowedSlug:'rodeio'}),/Caminho inválido/);assert.equal(await readFile(join(f.root,'rodeio/index.html'),'utf8'),'authorized Rodeio');}));
test('global allow cannot select any preview',t=>run(t,async f=>{await assert.rejects(preserveDevIziSnapshots({...f,allowedSlug:'all'}),/Slug dev não autorizado/);}));
test('missing expected generated HTML is not silently restored',t=>run(t,async f=>{await rm(join(f.root,f.manifest.replacements[1].path));await assert.rejects(preserveDevIziSnapshots({...f,allowedSlug:'rodeio'}),{code:'ENOENT'});const first=f.manifest.replacements[0];assert.equal(hash(await readFile(join(f.root,first.path))),first.generatedSha256);}));
