import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);
let playwright;try{playwright=require('playwright')}catch{playwright=require(process.env.JUMPER_PLAYWRIGHT||'/Users/marajah/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')}
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output=path.join(root,'data/visual-review');await fs.mkdir(output,{recursive:true});
const base=process.env.PREVIEW_URL||'http://127.0.0.1:4327';
const browser=await playwright.chromium.launch({headless:true,...(!existsSync(playwright.chromium.executablePath())?{channel:'chrome'}:{})});
const report={date:new Date().toISOString(),checks:[],errors:[],short_viewports:[]};
const check=(ok,label)=>{if(!ok)throw new Error(label);report.checks.push(label)};
try{
  const context=await browser.newContext({viewport:{width:1440,height:960}});
  const page=await context.newPage();page.on('pageerror',error=>report.errors.push(error.message));
  await page.goto(base,{waitUntil:'domcontentloaded'});
  check(await page.locator('.hero-slide img[src]').count()===1,'Carregamento: apenas a primeira cena tem src no início');
  await page.locator('[data-slideshow-ready]').waitFor();
  await page.evaluate(()=>document.fonts.ready);
  await page.waitForFunction(()=>[...document.querySelectorAll('.immersive-title .hero-line>span')].every(line=>line.getAnimations().every(animation=>animation.playState==='finished')));
  const hiddenMark=await page.addStyleTag({content:'.site-header .brand{visibility:hidden}'});
  await page.screenshot({path:path.join(output,'hero-print-no-logo.png')});
  await hiddenMark.evaluate(style=>style.remove());
  await page.getByRole('link',{name:'Nossa história',exact:true}).hover();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.desktop-nav .nav-print-original .nav-glyph')).transform!=='none');
  await page.screenshot({path:path.join(output,'motion-menu-hover.png')});
  check(await page.getByRole('link',{name:'Nossa história',exact:true}).count()===1,'Hover do menu: rótulo acessível único, sem duplicar as letras visuais');
  await page.locator('.hero-primary').hover({position:{x:15,y:20}});
  check(await page.locator('.hero-primary').evaluate(button=>Math.abs(parseFloat(button.style.getPropertyValue('--ink-x'))-15)<2),'Hover do botão: tinta nasce no ponto real do mouse');
  await page.screenshot({path:path.join(output,'motion-button-hover.png')});
  await page.locator('[data-slideshow-pause]').click();
  await page.locator('.photo-button').first().evaluate(element=>element.scrollIntoView({behavior:'instant',block:'center'}));
  await page.waitForFunction(()=>document.querySelector('.photo-button').classList.contains('is-revealed'));
  await page.locator('.photo-button').first().hover();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.photo-button'),'::after').opacity==='1');
  check(await page.locator('.photo-button .photo-reveal-strip').first().evaluate(strip=>getComputedStyle(strip).transform!=='none'),'Rolagem: fotografia abre as faixas da embalagem');
  await page.locator('.editorial-gallery').screenshot({path:path.join(output,'motion-photo-hover.png')});
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  await page.locator('[data-scene-select="1"]').click();
  await page.locator('[data-scene-select="2"]').click();
  await page.locator('[data-scene-select="0"]').click();
  await page.waitForFunction(()=>document.querySelector('[data-scene="0"]').classList.contains('is-active'));
  check(await page.locator('[data-scene-select="0"]').getAttribute('aria-pressed')==='true','Slideshow: seleção rápida respeita a última escolha');
  await page.locator('[data-slideshow-pause]').click();
  await page.locator('.hero-primary').focus();await page.mouse.move(900,240);
  await page.waitForFunction(()=>document.querySelector('[data-slideshow]').dataset.playback==='playing');
  await page.locator('.hero-primary').evaluate(()=>window.scrollTo({top:1800,behavior:'instant'}));
  await page.waitForFunction(()=>document.querySelector('[data-slideshow]').dataset.playback==='paused');
  check(await page.locator('[data-slideshow]').getAttribute('data-playback')==='paused','Slideshow: autoplay pausa fora do viewport');
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  await page.waitForFunction(()=>document.querySelector('[data-slideshow]').dataset.playback==='playing');
  await page.evaluate(()=>document.querySelector('#mobile-navigation').showModal());
  await page.waitForFunction(()=>document.querySelector('[data-slideshow]').dataset.playback==='paused');
  check(await page.locator('[data-slideshow]').getAttribute('data-playback')==='paused','Slideshow: diálogo aberto interrompe autoplay');
  await page.keyboard.press('Escape');
  await page.getByRole('link',{name:'Cardápio',exact:true}).first().click();
  await page.waitForURL('**/menu/');
  await page.waitForFunction(()=>document.querySelector('h1').getAnimations({subtree:true}).every(animation=>animation.playState==='finished'));
  check(await page.locator('h1').isVisible()&&await page.locator('[data-menu-item]').count()===83,'Transição de página: navega sem bloquear ou ocultar o cardápio');
  await context.close();
  for(const viewport of [{width:320,height:568},{width:320,height:500},{width:844,height:390},{width:1440,height:600}]){
    const compact=await browser.newContext({viewport,reducedMotion:'reduce'});const small=await compact.newPage();
    await small.goto(base,{waitUntil:'networkidle'});
    const bounds=await small.evaluate(()=>{
      const header=document.querySelector('.site-header').getBoundingClientRect(),copy=document.querySelector('.immersive-copy').getBoundingClientRect();
      const clipped=[...document.querySelectorAll('.hero-controls button,.immersive-actions a')].filter(element=>{const r=element.getBoundingClientRect();return r.x<0||r.right>innerWidth||r.bottom>innerHeight||r.height<43.5||r.width<43.5}).map(element=>element.getAttribute('aria-label')||element.textContent.trim());
      return {width:innerWidth,height:innerHeight,hero:document.querySelector('.immersive-hero').getBoundingClientRect().toJSON(),headerBottom:header.bottom,copyTop:copy.top,clipped};
    });
    report.short_viewports.push(bounds);
    check(bounds.clipped.length===0&&bounds.copyTop>=bounds.headerBottom-1,`Hero baixa ${viewport.width}×${viewport.height}: textos/controles não colidem ou cortam`);
    await small.screenshot({path:path.join(output,`hero-short-${viewport.width}-${viewport.height}.png`)});
    await compact.close();
  }
  const failed=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const resilient=await failed.newPage();
  await failed.route('**/images/cafe-*.webp',route=>route.abort());
  await resilient.goto(base,{waitUntil:'networkidle'});
  await resilient.locator('[data-scene-select="1"]').click();
  await resilient.waitForFunction(()=>document.querySelector('[data-slideshow]').dataset.playback==='paused');
  check(await resilient.locator('[data-scene="0"]').getAttribute('aria-hidden')==='false','Falha de rede: foto indisponível não apaga a cena atual');
  await resilient.locator('[data-scene-select="2"]').click();
  await resilient.waitForFunction(()=>document.querySelector('[data-scene="2"]').classList.contains('is-active'));
  check(await resilient.locator('[data-scene="2"] img').evaluate(image=>image.naturalWidth>0),'Falha de rede: outra fotografia continua selecionável');
  await resilient.screenshot({path:path.join(output,'hero-mobile-mesa.png')});
  await failed.close();
  const delayed=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const latest=await delayed.newPage();
  await delayed.route('**/images/cafe-*.webp',async route=>{await new Promise(resolve=>setTimeout(resolve,650));await route.continue()});
  await latest.goto(base,{waitUntil:'networkidle'});
  await latest.locator('[data-scene-select="1"]').click();
  await latest.locator('[data-scene-select="0"]').click();
  await latest.waitForFunction(()=>document.querySelector('[data-scene="1"] img').naturalWidth>0);
  check(await latest.locator('[data-scene="0"]').getAttribute('aria-hidden')==='false','Slideshow: carregamento atrasado não sobrescreve a última escolha');
  await delayed.close();
}catch(error){report.errors.push(error.stack||error.message)}
finally{await browser.close();await fs.writeFile(path.join(output,'motion-report.json'),JSON.stringify(report,null,2));}
console.log(JSON.stringify({checks:report.checks.length,errors:report.errors,short_viewports:report.short_viewports},null,2));
if(report.errors.length)process.exitCode=1;
