import {octoberArchivePhotos} from './october-archive-photos';
import {jardinsArchivePhotos} from './jardins-archive-photos';
import menuArrozRodeio from '../../briefing/entrada/matrizes/menuArrozRodeio.webp';
import jardinsNovoEncontro from '../../briefing/entrada/matrizes/jardinsNovoEncontro.webp';
import jardinsNovoAmbiente from '../../briefing/entrada/matrizes/jardinsNovoAmbiente.webp';
import iguatemiMesa from '../../briefing/entrada/matrizes/iguatemiMesa.webp';
import fachada from '../../briefing/entrada/matrizes/fachada.webp';
import mesa from '../../briefing/entrada/matrizes/mesa.webp';
import picanha from '../../briefing/entrada/matrizes/picanha.webp';
import servico from '../../briefing/entrada/matrizes/servico.webp';
import sobremesa from '../../briefing/entrada/matrizes/sobremesa.webp';
import historia from '../../briefing/entrada/matrizes/historia.webp';
import origem from '../../briefing/entrada/matrizes/origem.webp';
import bar from '../../briefing/entrada/matrizes/bar.webp';
import reservas from '../../briefing/entrada/matrizes/reservas.webp';
import historiaHero from '../../briefing/entrada/matrizes/historiaHero.webp';
import livroCardapio from '../../briefing/entrada/matrizes/livroCardapio.webp';
import carneDetalhe from '../../briefing/entrada/matrizes/carneDetalhe.webp';
import sobremesaServico from '../../briefing/entrada/matrizes/sobremesaServico.webp';
import mesaDetalhe from '../../briefing/entrada/matrizes/mesaDetalhe.webp';
import jardinsGallery from '../../briefing/entrada/matrizes/jardinsGallery.webp';
import jardinsSala from '../../briefing/entrada/matrizes/jardinsSala.webp';
import iguatemiAcervo from '../../briefing/entrada/matrizes/iguatemiAcervo.webp';
import jardinsJanela from '../../briefing/entrada/matrizes/jardinsJanela.webp';
import jardinsMesaDois from '../../briefing/entrada/matrizes/jardinsMesaDois.webp';
import jardinsMesaNoite from '../../briefing/entrada/matrizes/jardinsMesaNoite.webp';
import jardinsPassagem from '../../briefing/entrada/matrizes/jardinsPassagem.webp';
import jardinsLounge from '../../briefing/entrada/matrizes/jardinsLounge.webp';
import historiaFamilia from '../../briefing/entrada/matrizes/historia-familia.jpg';
import historiaRetrato from '../../briefing/entrada/matrizes/historia-retrato.jpg';
import historiaFachadaAcervo from '../../briefing/entrada/matrizes/historia-fachada-acervo.jpg';
import homeSalaAcervo2024 from '../../briefing/entrada/matrizes/home-sala-acervo-2024.webp';
import homeBifeAcervo2024 from '../../briefing/entrada/matrizes/home-bife-acervo-2024.webp';
import homeAperitivosAcervo2024 from '../../briefing/entrada/matrizes/home-aperitivos-acervo-2024.webp';
import homeCosteletasAcervo2024 from '../../briefing/entrada/matrizes/home-costeletas-acervo-2024.webp';
import homeMarcaAcervo2024 from '../../briefing/entrada/matrizes/home-marca-acervo-2024.webp';
import homeSobremesaAcervo2023 from '../../briefing/entrada/matrizes/home-sobremesa-acervo-2023.webp';
const {homePicanhaFatiada,homeArrozRodeio,menuCortes,cardapioHero}=octoberArchivePhotos;
const iguatemi=octoberArchivePhotos.iguatemiAcervoDsc9458;
const iguatemiHero=octoberArchivePhotos.iguatemiAcervoDsc9452;
const iguatemiDirectory=octoberArchivePhotos.iguatemiAcervoDsc9461;
const jardins=jardinsArchivePhotos.jardinsAcervoBmm21;
const jardinsHero=jardinsArchivePhotos.jardinsAcervoBmm17;
const jardinsDirectory=jardinsArchivePhotos.jardinsAcervoBmm33;
const reservasHero=jardinsArchivePhotos.jardinsAcervoBmm87;
export const photos = {...octoberArchivePhotos,...jardinsArchivePhotos,homePicanhaFatiada,homeArrozRodeio,menuCortes,menuArrozRodeio,jardinsNovoEncontro,jardinsNovoAmbiente,iguatemiMesa,fachada,jardins,iguatemi,mesa,picanha,servico,sobremesa,historia,origem,bar,reservas,jardinsHero,historiaHero,cardapioHero,livroCardapio,carneDetalhe,sobremesaServico,mesaDetalhe,jardinsDirectory,iguatemiDirectory,jardinsGallery,jardinsSala,iguatemiHero,iguatemiAcervo,reservasHero,jardinsJanela,jardinsMesaDois,jardinsMesaNoite,jardinsPassagem,jardinsLounge,historiaFamilia,historiaRetrato,historiaFachadaAcervo,homeSalaAcervo2024,homeBifeAcervo2024,homeAperitivosAcervo2024,homeCosteletasAcervo2024,homeMarcaAcervo2024,homeSobremesaAcervo2023};
export type PhotoName = keyof typeof photos;
