import type {PhotoName} from './photos';
type GalleryEntry={name:PhotoName;caption:string};
export const restaurantGalleries:Record<string,GalleryEntry[]>={
 jardins:[
  {name:'jardinsAcervoBmm12',caption:'A fachada do novo Jardins'},
  {name:'jardinsAcervoBmm18',caption:'Mesas e luz natural'},
  {name:'jardinsAcervoBmm29',caption:'O lounge dos Jardins'},
  {name:'jardinsAcervoBmm46',caption:'O balcão e a coleção do bar'},
  {name:'jardinsAcervoBmm53',caption:'O cuidado na mesa posta'},
  {name:'jardinsAcervoBmm87',caption:'O novo Jardins em movimento'},
  {name:'jardinsAcervoBmm13',caption:'O letreiro na entrada'},
  {name:'jardinsAcervoBmm14',caption:'O acesso à casa'},
  {name:'jardinsAcervoBmm15',caption:'Madeira e luz na fachada'},
  {name:'jardinsAcervoBmm16',caption:'A fachada entre as árvores'},
  {name:'jardinsAcervoBmm17',caption:'O salão sob a claraboia'},
  {name:'jardinsAcervoBmm19',caption:'O salão preparado para receber'},
  {name:'jardinsAcervoBmm20',caption:'A mesa e os tons da casa'},
  {name:'jardinsAcervoBmm21',caption:'À mesa, sob a luz do dia'},
  {name:'jardinsAcervoBmm22',caption:'A claraboia e o salão'},
  {name:'jardinsAcervoBmm23',caption:'Luz natural entre as mesas'},
  {name:'jardinsAcervoBmm24',caption:'A passagem entre os ambientes'},
  {name:'jardinsAcervoBmm25',caption:'O caminho até o lounge'},
  {name:'jardinsAcervoBmm26',caption:'O lounge visto da passagem'},
  {name:'jardinsAcervoBmm27',caption:'Um espaço para conversar'},
  {name:'jardinsAcervoBmm28',caption:'O lounge e suas mesas'},
  {name:'jardinsAcervoBmm30',caption:'Entre o lounge e o salão'},
  {name:'jardinsAcervoBmm31',caption:'Ambientes que se encontram'},
  {name:'jardinsAcervoBmm32',caption:'A passagem junto ao lounge'},
  {name:'jardinsAcervoBmm33',caption:'À mesa, junto ao jardim'},
  {name:'jardinsAcervoBmm34',caption:'O salão e suas cortinas'},
  {name:'jardinsNovoAmbiente',caption:'As mesas do novo Jardins'},
  {name:'jardinsAcervoBmm36',caption:'A luz acolhedora do salão'},
  {name:'jardinsAcervoBmm37',caption:'As mesas e as obras da casa'},
  {name:'jardinsAcervoBmm38',caption:'A perspectiva do salão'},
  {name:'jardinsAcervoBmm39',caption:'Mesas sob o teto de madeira'},
  {name:'jardinsAcervoBmm40',caption:'O salão em outro olhar'},
  {name:'jardinsAcervoBmm41',caption:'Mesa posta à luz do dia'},
  {name:'jardinsAcervoBmm42',caption:'Um convite para sentar'},
  {name:'jardinsAcervoBmm43',caption:'Os tons claros do salão'},
  {name:'jardinsAcervoBmm44',caption:'O bar dos Jardins'},
  {name:'jardinsAcervoBmm45',caption:'Um olhar para o bar'},
  {name:'jardinsAcervoBmm47',caption:'O bar entre os ambientes'},
  {name:'jardinsAcervoBmm48',caption:'O corredor iluminado'},
  {name:'jardinsAcervoBmm49',caption:'Os detalhes da passagem'},
  {name:'jardinsAcervoBmm50',caption:'O lounge junto ao bar'},
  {name:'jardinsAcervoBmm51',caption:'Luz e textura no lounge'},
  {name:'jardinsAcervoBmm52',caption:'A arquitetura da claraboia'},
  {name:'jardinsAcervoBmm54',caption:'À mesa, junto à cortina'},
  {name:'jardinsAcervoBmm55',caption:'Madeira e luz no salão'},
  {name:'jardinsAcervoBmm56',caption:'O salão junto ao jardim'},
  {name:'jardinsAcervoBmm57',caption:'Uma mesa perto do jardim'},
  {name:'jardinsAcervoBmm58',caption:'O encontro entre salão e lounge'},
  {name:'jardinsAcervoBmm59',caption:'Os detalhes do bar'},
  {name:'jardinsAcervoBmm60',caption:'A coleção de garrafas'},
  {name:'jardinsAcervoBmm61',caption:'Mesas baixas no lounge'},
  {name:'jardinsAcervoBmm62',caption:'Arte e mesa posta'},
  {name:'jardinsAcervoBmm63',caption:'À mesa, com luz acolhedora'},
  {name:'jardinsAcervoBmm64',caption:'O salão à meia-luz'},
  {name:'jardinsAcervoBmm65',caption:'Mesa posta para o encontro'},
  {name:'jardinsAcervoBmm66',caption:'A vegetação junto ao salão'},
  {name:'jardinsAcervoBmm67',caption:'Luz, madeira e verde'},
  {name:'jardinsAcervoBmm68',caption:'A mesa sob a luz da cortina'},
  {name:'jardinsAcervoBmm69',caption:'Taças e detalhes à mesa'},
  {name:'jardinsAcervoBmm70',caption:'Uma luz para a conversa'},
  {name:'jardinsAcervoBmm71',caption:'Os ambientes vistos do salão'},
  {name:'jardinsAcervoBmm72',caption:'A mesa e os espaços da casa'},
  {name:'jardinsAcervoBmm73',caption:'Um canto do lounge'},
  {name:'jardinsAcervoBmm74',caption:'Uma mesa e a arte da casa'},
  {name:'jardinsAcervoBmm75',caption:'Um olhar entre os ambientes'},
  {name:'jardinsAcervoBmm76',caption:'A luz sobre a mesa do lounge'},
  {name:'jardinsAcervoBmm77',caption:'A textura da arquitetura'},
  {name:'jardinsAcervoBmm78',caption:'Madeira e luz nos detalhes'},
  {name:'jardinsAcervoBmm79',caption:'O cuidado da equipe no salão'},
  {name:'jardinsAcervoBmm80',caption:'A equipe preparando a casa'},
  {name:'jardinsAcervoBmm81',caption:'O serviço em movimento'},
  {name:'jardinsAcervoBmm82',caption:'À mesa, com a equipe da casa'},
  {name:'jardinsAcervoBmm83',caption:'Os Jardins vistos da rua'},
  {name:'jardinsAcervoBmm84',caption:'Encontros no novo Jardins'},
  {name:'jardinsAcervoBmm85',caption:'A casa recebendo seus convidados'},
  {name:'jardinsAcervoBmm86',caption:'A vida ao redor das mesas'},
  {name:'jardinsNovoEncontro',caption:'Encontros à mesa no novo Jardins'},
 ],
 iguatemi:[
  {name:'iguatemi',caption:'O salão do Iguatemi'},
  {name:'iguatemiDirectory',caption:'Mesas e vegetação'},
  {name:'iguatemiHero',caption:'A casa em movimento'},
  {name:'iguatemiMesa',caption:'À mesa no Iguatemi'},
  {name:'iguatemiAcervo',caption:'A coleção que compõe a casa'},
 ]
};
